### ISSUE TITLE
The Expected parameters for 'change-password' were not supplied

### ISSUE THREAD

**Issue by dinc5150** [aaronpowell/Chauffeur#31]
I've been using Chauffeur on my 7.2.8 websites and its been working great, however, I've just used it in  a 7.3.0-RC site and cant seem to update the default password.

It creates the default SQL CE database fine, but when I run the command "user change-password 0 default newpass" I get the error "The Expected parameters for 'change-password' were not supplied. Format Expected: change-password <user Id> <old password> <new password>"

Chauffeur 0.6.3 installed via nuget

Any ideas?

**Comment by aaronpowell** [comment]
Ah sorry, I forgot to update the documentation after I refactored the way it worked. Chauffeur now uses the `IUserService` rather than the membership provider. I'll get the doco (and error message) fixed tonight but the new structure is:

    umbraco> user change-password <username> <new password>

You no longer need to provide the old password. It also works off the username (eg: `admin`).

**Comment by dinc5150** [comment]
Thanks Arron,
I should have run the help command as it was updated there. Thanks going to be much more useful being able to use the username instead.

I'm still getting my head around Git, so thought it was a good opportunity to try out a pull request to fix the change. Let me know if my pull request with the change is done right.

**Comment by aaronpowell** [comment]
Yep it was all good, it's merged and just going through the CI pipeline at the moment, so you'll see release `0.6.4` up on NuGet shortly (if it's not already). You can also cross-link GitHub issues with PR's by tagging them, such as #32 which is now merged :smile:

**Comment by dinc5150** [comment]
Great. Thanks for the tip!
