### ISSUE TITLE
Nested document types

### ISSUE THREAD

**Issue by vovikdrg** [aaronpowell/Chauffeur#33]
It seems that nested document types are not supported.

**Comment by aaronpowell** [comment]
Can you provide an example XML that is having issues?

**Comment by aaronpowell** [comment]
I've just published a new release, `0.7.0` to NuGet that changes the way doc types are imported and _may_ fix this.

Can you update to that build and see if it's fixed, and if not can you provide the XML that is failing?

**Comment by aaronpowell** [comment]
Closing this as I believe PR #35 and the `0.7.0` release solves this
