### ISSUE TITLE
Package deliverable error if composed doctype parent hasn't been added

### ISSUE THREAD

**Issue by markmc27** [aaronpowell/Chauffeur#36]
Hey Aaron,

I've been banging my head off the wall with this all day. I created a custom package in Umbraco with docTypes that are composed from a base docType.

I was having trouble importing the package using Chauffeur, but it would import without an issue when using the Umbraco backoffice functionality. 

The package deliverable code loops through the doctype elements in the package xml and adds them on a first-in-first-out basis, I think this may need updating to find any base types first and import those before loading the doctypes that have compositions defined. 

As an arbitrary example, I've attached two package xml files, one that works and another that throws the exception. The 'RichTextPage' doctype is composed of the 'BasePage' doctype and if Chauffeur tries to load the 'RichTextPage' before the 'BasePage', the import fails (as it should). Although an arbitrary example, this was a real issue where I had a doctype that was declared in the xml before the 'BasePage' and the import failed. 

Let me know if you are able to replicate it/need more info. I'll be happy to help with a solution too if needed. 

[Chauffeur.zip](https://github.com/aaronpowell/Chauffeur/files/611575/Chauffeur.zip)

**Comment by aaronpowell** [comment]
Sounds like this is the same as #33, will look at them together

**Comment by aaronpowell** [comment]
I've got a fix for this as part of #35 (I wrote an integration test to cover it and fixed the problem). I'm just having some issues with my CI pipeline at the moment so I can't publish new releases. Once I get those sorted I'll get it in and it'll all be fixed.

**Comment by aaronpowell** [comment]
Alright - got it publishing to NuGet: https://www.nuget.org/packages/Chauffeur/0.7.0-tests-rework-39

If you want to test with that (and the equivalent runner package) I'd like to know if it works 😄

**Comment by markmc27** [comment]
Just tested this, works perfectly. Thanks for the update! 😃

**Comment by aaronpowell** [comment]
And version 0.7.0 is out as stable, NuGet update will get you the release
