### ISSUE TITLE
Dictionary Deliverable

### ISSUE THREAD

**Issue by markmc27** [aaronpowell/Chauffeur#41]
Hey Aaron! 

I've completed the dev for the dictionary deliverable, minus the completed F# tests (I've been really busy and haven't had time to properly get my head around F#). 

Any chance I could push the branch for review? 

Cheers,

Mark (@MarkMcD27)

**Comment by aaronpowell** [comment]
Sure - send the PR through and I can have a review, and possibly add the tests after the fact :)

**Comment by aaronpowell** [comment]
Closed with PR #42 and release [0.8.0](https://www.nuget.org/packages/Chauffeur/0.8.0)
