### ISSUE TITLE
User deliverables

### ISSUE THREAD

**Issue by aDotNetDeveloper** [aaronpowell/Chauffeur#48]
looking at adding this command to user

add-user <username> <emailaddress> <password> <groupname> [<section> <section...]

but, there are many user related operations i need to do as part of a initial setup - unless i revert back to sql scripts yuk!

so would it be more feasible to have the ability of plugins ?

register a plugin for a specific deliverable which extends the command range without bloating the core of Chauffeur

thoughts ?
W

**Comment by aaronpowell** [comment]
Chauffeur already has a plugin model, see https://github.com/aaronpowell/Chauffeur/wiki/how-to-hello-world.

Admittedly this doesn't fully cover the scenario you're mentioning, it's about creating an entirely new command, say `user-extended`, not adding an operation to an existing command.

Adding an operation to a command would be really quite hard, it'd need some kind of operation resolver that is injected into the command (Deliverable) instance that you can then invoke.

Ultimately I think _that_ is more of an edge case to be solved so it's not something I'd look to prioritise, I believe the current extensibility model solves this in a suitable way without undue complexity.

If there is specific operations that you think are missing that are of benefit to everyone though I'm happy to include them :).

**Comment by aDotNetDeveloper** [comment]
yeah the new command plugin is what Ive done in the past, the ability of having the same constructor signature and get a IUserService passed in would be great... 

thats cool just wanted your thoughts on this - i have idea of how this could be implemented, but this can wait till another time.

Im happy to add more user operations for the benefit of all.

I also see my cut&paste of my add-user command failed - lol

**Comment by aaronpowell** [comment]
You could use the same constructor in your own deliverable, and if I was to create some injectable operation you would still not have to have a consistent constructor.

I'm going to close this for now, since there is an adequate work-around.
