### ISSUE TITLE
Runner defaults to Chauffeur 0.9.0

### ISSUE THREAD

**Issue by aDotNetDeveloper** [aaronpowell/Chauffeur#49]
Resolved actions to install package 'Chauffeur.Runner.0.9.0'
Retrieving package **'Chauffeur 0.9.0'** from 'nuget.org'.
Retrieving package 'Chauffeur.Runner 0.9.0' from 'nuget.org'.

**Comment by aaronpowell** [comment]
Hmm weird. Let me look into AppVeyor

**Comment by aaronpowell** [comment]
Seems there's an issue pushing to Symbol Source which means that the runner never published. Trying some tweaks now.

**Comment by aaronpowell** [comment]
Alright, build is finally fixed: https://ci.appveyor.com/project/aaronpowell/chauffeur/build/0.0.73

Now have a `0.10.1` release: https://www.nuget.org/packages/Chauffeur.Runner/0.10.1
