### ISSUE TITLE
Connection string as a CLI argument

### ISSUE THREAD

**Issue by random82** [aaronpowell/Chauffeur#52]
The current version requires valid connection string in web.config. It makes Umbraco/VSTS continuous delivery scenario more complex when using WebDeploy - WebDeploy doesn't leave transformed web.config on the deployment agent (which makes sense).

Therefore, the only approach I found, a quite ugly one, is to unzip WD package, transform web.config outside of webDeploy, zip it back and use webDeploy after that.

It will be helpful if Chauffeur took a connection string argument, so at least web.config transformation outside of webDeploy wouldn't be required.

Something like:
`-c "<connection string>"`

Since, I update Umbraco DB connection string from the VSTS CD pipeline, I will have a consistent argument going to both - webDeploy and Chauffeur

**Comment by aaronpowell** [comment]
I've merged this into master and cut version `0.11.0` that contains it
