### ISSUE TITLE
Doesnt work against umbraco 7.7.7

### ISSUE THREAD

**Issue by stuartcrouch** [aaronpowell/Chauffeur#67]
Started at a new company where we want to spin up umbraco from scratch
Chauffeur seemed perfect for this but it doesnt work with 7.7.7. It complains of an automapper inconsistency

```
PS C:\Users\Stuart\source\repos\GVUmbraco\CoffeeLovers\bin> .\Chauffeur.Runner.exe

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'AutoMapper, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

 I tried building against the new version of umbraco, but the compiler complains that 

```
Build started 07/01/2018 21:12:17.
     1>Project "C:\src\Chauffeur\Chauffeur.sln" on node 1 (Build target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|Any CPU".
       ValidateProjects:
         The project "Chauffeur.Demo" is not selected for building in solution configuration "Release|Any CPU".
     1>Project "C:\src\Chauffeur\Chauffeur.sln" (1) is building "C:\src\Chauffeur\Chauffeur\Chauffeur.csproj" (2) on node 1 (default targets).
     2>PrepareForBuild:
         Creating directory "bin\Release\".
     1>Project "C:\src\Chauffeur\Chauffeur.sln" (1) is building "C:\src\Chauffeur\Chauffeur.Tests.Integration\Chauffeur.Tests.Integration.fsproj" (3) on node 4 (default targets).
     3>C:\src\Chauffeur\Chauffeur.Tests.Integration\Chauffeur.Tests.Integration.fsproj(55,3): error MSB4020: The value "" of the "Project" attribute in element <Import> is invalid.
```

**Comment by stuartcrouch** [comment]
If its easy to get the missing value into the project I'll send a pull request, but I have no idea what the actual problem is here.

**Comment by aaronpowell** [comment]
I'm assuming you're using the latest (stable) Chauffeur `0.12.2`?

What version of .NET is your the project?

I've just created a new .NET 4.6.2 project, installed Umbraco 7.7.7 and Chauffeur.Runner (and Chauffeur) 0.12.2, and it worked just fine.

**Comment by aaronpowell** [comment]
It's not possible to provide access to your codebase that has the problem is it?

**Comment by aaronpowell** [comment]
Oh and regarding the build log:

- I disable the `Chauffeur.Demo` project in the `Release` build, as that's what runs on the build server and on there I have no need to compile it
- The 'error' with the Integration Tests project is a non-fatal one, something's changed in the project system that I haven't found yet, and being non-fatal I didn't stress (F# has something break every other day it seems)

**Comment by stuartcrouch** [comment]
https://gitlab.com/stuartcrouch/chauffeur-test

I've just dumped a copy of one that doesnt work into gitlab

Its using Chauffeur 0.12.2.0 and is on .NET 4.6.2.

I'll try starting completely from scratch and see what happens.

**Comment by aaronpowell** [comment]
I've done a bit of digging, it looks like the problem is coming from the `Umbraco.RestApi` NuGet package, it's referencing `AutoMapper@3.0.0.0`.

There's a binding redirect in the Web.config that *should* be taking care of it, but evidently it isn't, and I'm trying to work out why.

**Comment by aaronpowell** [comment]
_For my own future reference_

Here's the fuslogvw output:

```
*** Assembly Binder Log Entry  (8/01/2018 @ 12:03:30) ***

The operation failed.
Bind result: hr = 0x80131040. No description available.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\_Projects\chauffeur-error\chauffeur-test\CoffeeLovers\bin\Chauffeur.Runner.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = AutoMapper, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/_Projects/chauffeur-error/chauffeur-test/CoffeeLovers/bin/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = Chauffeur.Runner.exe
Calling assembly : Umbraco.RestApi, Version=1.0.5779.34030, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\_Projects\chauffeur-error\chauffeur-test\CoffeeLovers\bin\Chauffeur.Runner.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/_Projects/chauffeur-error/chauffeur-test/CoffeeLovers/bin/AutoMapper.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\_Projects\chauffeur-error\chauffeur-test\CoffeeLovers\bin\AutoMapper.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: AutoMapper, Version=3.3.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005
WRN: Comparing the assembly name resulted in the mismatch: PUBLIC KEY TOKEN
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

**Comment by aaronpowell** [comment]
Actually, thinking about this more, does the web even work? It should error with the same problem, because you've got an implicit reference on `AutoMapper@3.0.0` that is **unsigned** and an explicit reference to `AutoMapper@3.3.1.0` that is **signed**.

So while you've got a `<bindingRedirect>` in the web.config it doesn't work because the public key will cause a problem (the above referenced error).

The latest commits shows the project has been updated to a newer AutoMapper version, @shazwazza - any idea when `UmbracoCms.RestApi` could see a NuGet package update?

**Comment by Shazwazza** [comment]
We re-bind automapper in code because they signed their assemblies mid-way through a major release :( so the only way to redirect is via code. In Umbraco this is how we do it: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/BindingRedirects.cs 

The RestApi project will not get an update but there will be a major release probably soon (ish) You should be able to fix the binding redirect problem with code

**Comment by aaronpowell** [comment]
Well... balls 😧.

I'll have to patch the Chauffeur.Runner to do that.

**Comment by aaronpowell** [comment]
@stuartcrouch I've patched the Chauffeur.Runner app with the stuff @Shazwazza linked to and published a pre-release NuGet package: https://www.nuget.org/packages/Chauffeur.Runner/0.12.3-binding-re-124

I did a quick test with the code you shared and it looks all good, can you test too? If it's all good I'll merge and cut a `0.12.3` as stable.

**Comment by stuartcrouch** [comment]
Hi. This works using 0.12.3-binding-re-124.

**Comment by aaronpowell** [comment]
New stable release, `0.12.3` is now up on NuGet 😄 

https://www.nuget.org/packages/Chauffeur/0.12.3
