### ISSUE TITLE
ChauffeurRunner.exe crashes

### ISSUE THREAD

**Issue by TFAstudio** [aaronpowell/Chauffeur#74]
Process to replicate

Open new project
```
nuget install UmbracoCMS 7.11.1
nuget install Chauffeur 1.1.1
nuget install Chauffeur.Runner 1.1.1
nuget install Chauffeur.TestingTools 1.1.1
```

Open PowerShell
change to root directory of project, 
Run runner using `.\[project_name]\bin\Chauffeur.Runner.exe`

The following error came out:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Umbraco.Core, Version=1.0.6470.38234, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Chauffeur.ShittyIoC..ctor()
   at Chauffeur.Host.UmbracoHost..ctor(TextReader reader, TextWriter writer)
   at Chauffeur.Runner.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
   at Chauffeur.Runner.Program.Main(String[] args)
```

Is this not meant to be run with the latest version of Umbraco?  It says >= 7.7, but seems like the version of the latest assembly is 1.0.6750.39767, not what was expected above...  How to get around this?

**Comment by aaronpowell** [comment]
Hmm I thought I had tested against `7.11.1` and it was working.

I'll look into it when I get some time.

**Comment by TFAstudio** [comment]
What version should I use?

**Comment by TFAstudio** [comment]
I must be doing something really wrong ...

I have now gone to Umbraco 7.7.0 which has the correct assembly version for Umbraco.Core, yet I still get the same error, so I am unsure what to do to move forward

**Comment by aaronpowell** [comment]
It should work fine with the latest version of Umbraco

**Comment by TFAstudio** [comment]
Just noticed ... somehow the nuget install for Chauffeur removes the umbraco assemblies?  'upgrading' the Umbraco package puts them back in...  thanks, I don't know why I didn't check the bin directory

**Comment by aaronpowell** [comment]
Hi @TFAstudio - are you able to provide a repository that reproduces this issue? Otherwise I'm going to close it.

**Comment by aaronpowell** [comment]
Closing as I've been unable to reporduce
