### ISSUE TITLE
Add ability for Chauffeur to handle content (optional)

### ISSUE THREAD

**Issue by alanwthom** [aaronpowell/Chauffeur#98]
It would be nice if the scaffold deliverable provided an option to include current content in the XML export of the current installation. This would also require a change to the package deliverable to process the Documents node to import this content (if included).

**Comment by aaronpowell** [comment]
Chauffeur isn't really meant to working with Content, instead I have created a separate package, https://github.com/aaronpowell/chauffeur.contentimport, that handles content and it'd probably be better suited there.

Although, the current focus for me is v8 support and I haven't looked at upgrading the external plugins yet :(

**Comment by alanwthom** [comment]
Hi Aaron, thanks for the reply. Okay, that makes perfect sense. `Chauffeur.ContentImport` looks to do exactly what I'm after (importing content and republishing), but unsure whether an export of content is support by either this or the core `Chauffeur` package as I'd like to avoid exporting this via the Umbraco UI? 

[I've added some code to a fork](https://github.com/stormid/Chauffeur/commit/7ad8a9b51f5ae2fbde01a1e9fc1875d193b0cd8b) to both export and import content on the `scaffold` and `package` deliverables which was based on my original thoughts before raising this. If you have some time, and wouldn't mind, I'd be interested on your thoughts on this where my use-case is to use Chauffeur to spin-up a known-state site to run destructive tests against as part of a build process. If this is something you'd prefer to keep out of the package then I can look into creating a separate package with Chauffeur as a dependency.

Thanks

**Comment by aaronpowell** [comment]
My preference would be to put it into the ContentImport plugin (although the name is a bit misleading, might be better to eventually evolve it to just 'Content') as it keeps a clear separation in the intent of Chauffeur away from managing content deployments.

**Comment by alanwthom** [comment]
Okay, that makes sense. I'll raise a PR there instead. Thanks for your help!
